# Generated by Django 5.1.4 on 2025-01-21 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='photo',
        ),
    ]
