# Generated by Django 5.1.4 on 2025-01-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_cart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('pizza', 'pizza'), ('sushi', 'sushi'), ('salad', 'salad'), ('desert', 'desert'), ('burger', 'burger')], max_length=200),
        ),
    ]
