# Generated by Django 5.1.4 on 2025-01-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(default='/static/random-foods.jpg', upload_to=''),
        ),
    ]
