# Generated by Django 5.1.4 on 2025-01-11 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.CharField(choices=[('notdishpatched', 'notdishpatched'), ('dishpatched', 'dishpatched'), ('outfordel', 'outfordel'), ('deleivered', 'deleivered')], max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.cart')),
            ],
        ),
    ]
