# Generated by Django 5.1.4 on 2025-01-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
