# Generated by Django 5.1.4 on 2025-01-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_fooditem_img2_fooditem_img3'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('OutOfStock', 'OutOfStock')], default='available', max_length=50),
        ),
    ]
