# Generated by Django 5.1.4 on 2025-01-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_order_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='uwu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.TextField(default=8486510052),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='current',
            field=models.CharField(choices=[('notdishpatched', 'notdishpatched'), ('dishpatched', 'dishpatched'), ('outfordel', 'outfordel'), ('deleivered', 'deleivered')], default='notdishpatched', max_length=50),
        ),
    ]
