# Generated by Django 5.1.4 on 2025-01-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_alter_order_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='current',
            field=models.CharField(choices=[('notdishpatched', 'notdishpatched'), ('outfordel', 'outfordel'), ('deleivered', 'deleivered'), ('cancelled', 'cancelled')], default='notdishpatched', max_length=50),
        ),
    ]
