# Generated by Django 5.1.4 on 2025-01-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_alter_order_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.JSONField(),
        ),
    ]
