# Generated by Django 5.1.4 on 2025-01-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_alter_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='confirm',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
