# Generated by Django 5.1.4 on 2025-01-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='staff_level',
            field=models.CharField(choices=[('chef', 'Chef'), ('manager', 'Manager'), ('owner', 'Owner')], default='chef', max_length=50),
        ),
    ]
