# Generated by Django 5.1.4 on 2025-01-14 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_worker_staff_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='description',
            new_name='descriptions',
        ),
    ]
